FROM jenkins/jenkins:lts

USER root

# Install useful tools
RUN apt-get update && apt-get install -y jq \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy plugins list and install plugins
COPY jenkins-config/plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt

# Copy init groovy scripts for job creation
COPY jenkins-config/init.groovy.d/ /usr/share/jenkins/ref/init.groovy.d/

USER jenkins
